### ISSUE TITLE
Missing part of the response header

### ISSUE THREAD

**Issue by stevending1st** [EasyWebApp/KoAJAX#6]
```
headers: {
  Content-Length: "133",
  Content-Type: "application/json; charset=utf-8"
}
```

Lost `Access-Control-Allow-Origin`, `Alt-Svc`, `Date`, `Server`, `Vary`,

**Comment by TechQuery** [comment]
1. Which platform are you using? Web browsers or Node.js? It aims to find out which standard API is invoked:

https://github.com/EasyWebApp/KoAJAX/blob/8a8b3cca9ada8dafb99ac72abf7700e31bb1d56d/source/HTTPRequest.ts#L183-L187

2. Could you give me an example API to test the request？

**Comment by TechQuery** [comment]
Web standard HTTP API has some security limitation:
https://stackoverflow.com/questions/8945587/xmlhttprequest-getallresponseheaders-not-returning-all-the-headers

**Comment by TechQuery** [comment]
> Now I need to record the time of a http request in the browser, so I need to get the Data value of the response header.

Just write a Logger middleware:

```ts
new HTTPClient().use(async ({ request: { path } }, next) => {
    const title = `HTTP request: ${path}`;

    console.time(title);

    await next();

    console.timeEnd(title);
});
```

> Oddly enough, I can see Data in the browser's debugging tool, and I'm not sure if the library cropped the response header.

I never crop standard HTTP headers:

https://github.com/EasyWebApp/KoAJAX/blob/8a8b3cca9ada8dafb99ac72abf7700e31bb1d56d/source/HTTPRequest.ts#L107

https://github.com/EasyWebApp/KoAJAX/blob/8a8b3cca9ada8dafb99ac72abf7700e31bb1d56d/source/HTTPRequest.ts#L66-L78
